### ISSUE TITLE
Can't connect to Prismic

### ISSUE THREAD

**Issue by scottyzen** [ilrock/gridsome-source-prismic#1]
Any ideas on why I keep getting this error. I can't seem to get past it. Even when I cloned your starter repo (https://github.com/ilrock/gridsome-starter-prismic) and change the environment variable I'm still getting the same error. 

```
Initializing plugins...
TypeError: Cannot read property 'map' of undefined
    at /Users/scott/Desktop/gridsomePrismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:10413
    at /Users/scott/Desktop/gridsomePrismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:10571
    at Array.reduce (<anonymous>)
    at Function.value (/Users/scott/Desktop/gridsomePrismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:10236)
    at Object.t.default [as serialize] (/Users/scott/Desktop/gridsomePrismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:18916)
    at Object.asHtml (/Users/scott/Desktop/gridsomePrismic/node_modules/prismic-dom/dist/prismic-dom.min.js:1:4801)
    at Object.keys.forEach (/Users/scott/Desktop/gridsomePrismic/node_modules/@ilrock/gridsome-source-prismic/utils/index.js:110:40)
    at Array.forEach (<anonymous>)
    at documentParser (/Users/scott/Desktop/gridsomePrismic/node_modules/@ilrock/gridsome-source-prismic/utils/index.js:96:21)
    at results.forEach (/Users/scott/Desktop/gridsomePrismic/node_modules/@ilrock/gridsome-source-prismic/index.js:41:31)
    at Array.forEach (<anonymous>)
    at PrismicSource.loadCollections (/Users/scott/Desktop/gridsomePrismic/node_modules/@ilrock/gridsome-source-prismic/index.js:39:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

This is the way my config file looks
```javascript
module.exports = {
  siteName: 'Gridsome',
  plugins: [
    {
      use: 'gridsome-plugin-tailwindcss'
    },
    {
      use: "@ilrock/gridsome-source-prismic",
      options: {
        prismic_url: "https://siteurl.cdn.prismic.io/api/v2",
        prismic_token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        collection_prefix: "Prismic"
      }
    }
  ]
}

```

**Comment by ilrock** [comment]
Hey @scottyzen! How many document types do you have in Prismic? Can you please show me the data types that they use?

**Comment by scottyzen** [comment]
Just the two Repeatable types.


![Screenshot 2020-04-22 at 00 12 27](https://user-images.githubusercontent.com/5116925/79923759-2a399400-842e-11ea-893f-d9c48334c120.png)

**Comment by ilrock** [comment]
Thanks @scottyzen! What data types do they use? If I have the data types I can try and replicate the issue on my end

**Comment by scottyzen** [comment]
Thanks, I hope these are what you need.
Heres the first.
```json
{
  "Articles" : {
    "uid" : {
      "type" : "UID",
      "config" : {
        "label" : "UID",
        "placeholder" : "unique-identifier-for-blog-post-url"
      }
    },
    "title" : {
      "type" : "StructuredText",
      "config" : {
        "single" : "heading1",
        "label" : "Title",
        "placeholder" : "Page Title"
      }
    },
    "sub_title" : {
      "type" : "Text",
      "config" : {
        "label" : "Sub Title",
        "placeholder" : "Sub Title"
      }
    },
    "featured_image" : {
      "type" : "Image",
      "config" : {
        "constraint" : { },
        "thumbnails" : [ {
          "name" : "Small",
          "width" : 200,
          "height" : 200
        } ],
        "label" : "Featured Image"
      }
    },
    "date" : {
      "type" : "Date",
      "config" : {
        "label" : "Date"
      }
    },
    "body" : {
      "type" : "Slices",
      "fieldset" : "Slice zone",
      "config" : {
        "labels" : {
          "image_with_caption" : [ {
            "name" : "emphasized",
            "display" : "Emphasized"
          }, {
            "name" : "image-full-width",
            "display" : "Full"
          } ],
          "gallery" : [ ]
        },
        "choices" : {
          "text" : {
            "type" : "Slice",
            "fieldset" : "Text",
            "description" : "A rich text section",
            "icon" : "text_fields",
            "non-repeat" : {
              "text" : {
                "type" : "StructuredText",
                "config" : {
                  "multi" : "paragraph, preformatted, heading1, heading2, heading3, heading4, heading5, heading6, strong, em, hyperlink, image, embed, list-item, o-list-item, o-list-item",
                  "label" : "text"
                }
              }
            },
            "repeat" : { }
          },
          "image_with_caption" : {
            "type" : "Slice",
            "fieldset" : "Image with Caption",
            "description" : "An image with an optional caption",
            "icon" : "image",
            "non-repeat" : {
              "image" : {
                "type" : "Image",
                "config" : {
                  "constraint" : {
                    "width" : 1200
                  },
                  "thumbnails" : [ ],
                  "label" : "Image"
                }
              },
              "caption" : {
                "type" : "StructuredText",
                "config" : {
                  "single" : "heading3",
                  "label" : "Caption",
                  "placeholder" : "Image Caption..."
                }
              }
            },
            "repeat" : { }
          },
          "list_of_articles" : {
            "type" : "Slice",
            "fieldset" : "List of Articles",
            "description" : "Section title and article list",
            "icon" : "photo_filter",
            "non-repeat" : {
              "title_of_section" : {
                "type" : "StructuredText",
                "config" : {
                  "multi" : "heading2",
                  "label" : "Title of Section",
                  "placeholder" : "Featured"
                }
              }
            },
            "repeat" : {
              "articles_to_link" : {
                "type" : "Link",
                "config" : {
                  "label" : "Articles to link",
                  "placeholder" : "Selct your article"
                }
              }
            }
          },
          "quote" : {
            "type" : "Slice",
            "fieldset" : "Quote",
            "description" : "A short quote with author's portrait",
            "icon" : "add_alert",
            "non-repeat" : {
              "quote" : {
                "type" : "StructuredText",
                "config" : {
                  "single" : "em",
                  "label" : "Quote",
                  "placeholder" : "Your quote"
                }
              },
              "name_of_the_author" : {
                "type" : "StructuredText",
                "config" : {
                  "single" : "paragraph",
                  "label" : "Name of the author",
                  "placeholder" : "John Doe"
                }
              },
              "portrait_author" : {
                "type" : "Image",
                "config" : {
                  "constraint" : {
                    "width" : 700,
                    "height" : 700
                  },
                  "thumbnails" : [ {
                    "name" : "mobile",
                    "width" : 350,
                    "height" : 350
                  } ],
                  "label" : "Portrait Author"
                }
              }
            },
            "repeat" : { }
          },
          "gallery" : {
            "type" : "Slice",
            "fieldset" : "Gallery",
            "description" : "gallery",
            "icon" : "insert_photo",
            "display" : "grid",
            "non-repeat" : { },
            "repeat" : {
              "image" : {
                "type" : "Image",
                "config" : {
                  "constraint" : { },
                  "thumbnails" : [ {
                    "name" : "thumbnail",
                    "width" : 400,
                    "height" : 400
                  } ],
                  "label" : "Image"
                }
              }
            }
          }
        }
      }
    }
  },
  "Meta Data" : {
    "discription" : {
      "type" : "Text",
      "config" : {
        "label" : "Discription",
        "placeholder" : "Discription"
      }
    },
    "keywords" : {
      "type" : "Text",
      "config" : {
        "label" : "Keywords",
        "placeholder" : "One, Two, Three"
      }
    }
  }
}
```
and here's the other
```json
{
  "Main" : {
    "uid" : {
      "type" : "UID",
      "config" : {
        "label" : "Slug",
        "placeholder" : "Slug"
      }
    },
    "title" : {
      "type" : "StructuredText",
      "config" : {
        "single" : "heading1, heading2, heading3, heading4, heading5, heading6",
        "label" : "Title",
        "placeholder" : "Product Title"
      }
    },
    "product_label" : {
      "type" : "StructuredText",
      "config" : {
        "single" : "heading2, heading3, heading4, heading5, heading6",
        "label" : "Product Label",
        "placeholder" : "Product label"
      }
    },
    "price" : {
      "type" : "Number",
      "config" : {
        "label" : "Price",
        "placeholder" : "Price"
      }
    },
    "sale_price" : {
      "type" : "Number",
      "config" : {
        "label" : "Sale price",
        "placeholder" : "Sale price"
      }
    },
    "main_product_image" : {
      "type" : "Image",
      "config" : {
        "constraint" : { },
        "thumbnails" : [ {
          "name" : "Thumbnail",
          "width" : 400,
          "height" : 400
        } ],
        "label" : "Main Product Image"
      }
    },
    "related_products" : {
      "type" : "Link",
      "config" : {
        "select" : "document",
        "label" : "Related Products",
        "placeholder" : "Related Products"
      }
    },
    "body" : {
      "type" : "Slices",
      "fieldset" : "Slice zone",
      "config" : {
        "labels" : {
          "product_information" : [ {
            "name" : "product_info",
            "display" : "Product Info"
          } ]
        },
        "choices" : {
          "product_information" : {
            "type" : "Slice",
            "fieldset" : "Product Information",
            "description" : "Product information",
            "icon" : "info",
            "display" : "list",
            "non-repeat" : {
              "text" : {
                "type" : "StructuredText",
                "config" : {
                  "multi" : "paragraph, preformatted, heading1, heading2, heading3, heading4, heading5, heading6, strong, em, hyperlink, image, embed, list-item, o-list-item, o-list-item",
                  "label" : "Text"
                }
              }
            },
            "repeat" : { }
          }
        }
      }
    }
  }
}
```

**Comment by ilrock** [comment]
Hey @scottyzen! Yes, that is exactly what I was looking for. Thank you for sending them over.

So the reason why you're getting the error is that you are using the "Slices" type that is not yet supported (I detailed the supported data types in the main Readme). I'm actively working on the plugin to add support to slices soon. In the meanwhile a possible workaround could be to identify what information you need the slices to hold and add different data types according to the information itself

**Comment by scottyzen** [comment]
Ok @ilrock. Thanks for letting me know 👍🏻

**Comment by juliageek** [comment]
I cannot connect to Prismic either, but I don't have slices yet. So my approach is the following:
1. I put all variables needed by the source in an `.env` file. Then I set up `gridsome.server.js` like so:

```
module.exports = {
  plugins: [
    {
      use: "@ilrock/gridsome-source-prismic",
      options: {
        url: process.env.PRISMIC_API_URL,
        prismic_token: process.env.AUTH_TOKEN,
        collection_prefix: "Prismic"
      }
    }
  ]
};
```

Now, when I try to go to `http://localhost:8080/___explore` and call: 
```
query{
  Prismic {  
  	page(uid: "test", lang:"en-us") {
    	title, image
		}
  }
}
```
I get an error that `"message": "Cannot query field \"Prismic\" on type \"Query\"."`

**Comment by ilrock** [comment]
Hey @juliageek! So, likely that is because your collection is going to be called something else. For instance, if one of your **Custom Types** is called _Post_, then you can reference it in GraphQL as **PrismicPost**.

Does that make sense?

**Comment by juliageek** [comment]
Hi @ilrock Thanks for your reply. Actually, my issue was that I had to add the plugin in `gridsome.config.js` and I was not aware of that.

**Comment by djmtype** [comment]
I'm getting the same `TypeError: Cannot read property 'map' of undefined`. 

The only collection I have is `Post.`

I'm not using Prismic slices and my gridsome.config.js looks like this: 

```
require("dotenv").config()

module.exports = {
  templates: {
    PrismicPost: "/posts/:slug"
  },
  plugins: [
    {
      use: "@ilrock/gridsome-source-prismic",
      options: {
        prismic_url: process.env.PRISMIC_API_URL,
        prismic_token: process.env.PRISMIC_TOKEN,
        collection_prefix: "Prismic"
      }
    }
  ]
};
```

**Comment by djmtype** [comment]
This plugin, Prismic itself, and the official Gridsome/Prismic plugin refer to the API URL differently, and therefore, it's very confusing. It's also the reason for this map error. 

The PRISMIC_API_URL should be `https://yourprojectname.prismic.io/api` when using this plugin. It's the same URL that will take you to the Prismic playground. However, Prismic notes using this endpoint found within your dashboard: `https://ariatapprismic.cdn.prismic.io/api/v2`

The official [Gridsome/Prismic](https://gridsome.org/plugins/gridsome-source-graphql-prismic) plugin requires you don't append the `api` to the URL. Use like this instead: `https://your-repository.prismic.io`.

**Comment by rylanharper** [comment]
Any update on this? Like @djmtype I am also confused on what is exactly needed for the URL
